### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by meMuszr** [khellang/Scrutor#132] opened 2020-11-20 22:21 UTC
Document the default service lifetime is `Transient` if it's not explicitly defined. 

Had to jump through the code to find out the answer to this one as I couldn't find documentation outside of the `README`

If you have an idea of where to put this, I can take of it.

**Comment by khellang** [comment] 2020-11-22 12:03
Yeah, I haven't done a good job on documentation. A goal has always been to keep the library as simple as possible (with XML documentation) so I wouldn't have to provide a bunch of external documentation. So far, after 5 years, it's worked out pretty well 😅

I don't mind adding this to the README. If you'd like to send a PR, I'll happily accept it 👌

**Comment by khellang** [comment] 2021-03-16 23:48
I'm closing this as a duplicate of #107

**Closed by khellang** 2021-03-16 23:48 UTC
