### ISSUE TITLE
Question: How to decorate all classes that implement interface?

### ISSUE THREAD

**Issue by Jaap-van-Hengstum** [khellang/Scrutor#137] opened 2021-02-19 15:41 UTC
Suppose I have the following classes:

```c#
public interface IBase
{
    bool IsDecorated { get; set; }
}

public interface IFoo : IBase {}

public interface IBar : IBase {}

public class Foo : IFoo { ... }

public class Bar : IBar { ... }
```

I scan them using:

```c#
services.Scan(s => s.FromApplicationDependencies()
    .AddClasses(c => c.AssignableTo<IBase>()).AsMatchingInterface().WithSingletonLifetime());
```

so I can inject either `IFoo` or `IBar`, for example:

```c#
public class MyClass 
{
  public MyClass(IFoo foo)
  {
    ...
  }
}
```

I know I can decorate `IFoo` and `IBar` separately:

```c#
services.Decorate<IFoo>(x => {x.IsDecorated = true; return x;});
services.Decorate<IBar>(x => {x.IsDecorated = true; return x;});
```

But what I want is to decorate all classes that are assignable to `IBase`. 
Something like:

```c#
services.Decorate<IBase>(x => {x.IsDecorated = true; return x;});
```

The above statement doesn't work because `IBase` is not registered as a dependency.

Registering `IBase` as a dependency along with `IFoo` and `IBar` doesn't work also:

```c#
services.Scan(s => s.FromApplicationDependencies()
    .AddClasses(c => c.AssignableTo<IBase>()).AsImplementedInterfaces().WithSingletonLifetime());

services.Decorate<IBase>(x => {x.IsDecorated = true; return x;});
```

Because it only decorates `IBase` and not `IFoo` and `IBar`.

---
**How can I decorate all classes that are assignable to `IBase`?
I feel like I'm missing something.**

**Comment by khellang** [comment] 2021-03-16 23:40
Yeah, decorating everything assignable to the service type isn't supported. Currently it's decorating based on the same service type:

https://github.com/khellang/Scrutor/blob/a949cd24726cfb0bc081a95e1e33fb5b6ea05f94/src/Scrutor/ServiceCollectionExtensions.Decoration.cs#L312-L315

And changing this behavior today would be a big breaking change. This is likely not going to happen for a while 😞

**Comment by khellang** [comment] 2021-03-16 23:42
Ah, this seems like a duplicate of #46. I'll close this and keep that on open for tracking :)

**Closed by khellang** 2021-03-16 23:42 UTC
Labels: Breaking Change
